/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCostRouteImport } from './routes/_authenticated/cost'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedReferencesRouteImport } from './routes/_authenticated/references'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedComponentsIndexRouteImport } from './routes/_authenticated/components/index'
import { Route as AuthenticatedComponentsComponentIdRouteImport } from './routes/_authenticated/components/$componentId'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers/$customerId'
import { Route as AuthenticatedFormulasIndexRouteImport } from './routes/_authenticated/formulas/index'
import { Route as AuthenticatedFormulasFormulaIdRouteImport } from './routes/_authenticated/formulas/$formulaId'
import { Route as AuthenticatedIngredientsIndexRouteImport } from './routes/_authenticated/ingredients/index'
import { Route as AuthenticatedIngredientsIngredientIdRouteImport } from './routes/_authenticated/ingredients/$ingredientId'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders/$orderId'
import { Route as AuthenticatedProductionIndexRouteImport } from './routes/_authenticated/production/index'
import { Route as AuthenticatedProductionSessionIdRouteImport } from './routes/_authenticated/production/$sessionId'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedProductsProductIdRouteImport } from './routes/_authenticated/products/$productId'
import { Route as AuthenticatedSettingsCalibrationTechniqueIdRouteImport } from './routes/_authenticated/settings_.calibration.$techniqueId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCostRoute = AuthenticatedCostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferencesRoute = AuthenticatedReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComponentsIndexRoute =
  AuthenticatedComponentsIndexRouteImport.update({
    id: '/components/',
    path: '/components/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComponentsComponentIdRoute =
  AuthenticatedComponentsComponentIdRouteImport.update({
    id: '/components/$componentId',
    path: '/components/$componentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormulasIndexRoute =
  AuthenticatedFormulasIndexRouteImport.update({
    id: '/formulas/',
    path: '/formulas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormulasFormulaIdRoute =
  AuthenticatedFormulasFormulaIdRouteImport.update({
    id: '/formulas/$formulaId',
    path: '/formulas/$formulaId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIngredientsIndexRoute =
  AuthenticatedIngredientsIndexRouteImport.update({
    id: '/ingredients/',
    path: '/ingredients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIngredientsIngredientIdRoute =
  AuthenticatedIngredientsIngredientIdRouteImport.update({
    id: '/ingredients/$ingredientId',
    path: '/ingredients/$ingredientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionIndexRoute =
  AuthenticatedProductionIndexRouteImport.update({
    id: '/production/',
    path: '/production/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionSessionIdRoute =
  AuthenticatedProductionSessionIdRouteImport.update({
    id: '/production/$sessionId',
    path: '/production/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsProductIdRoute =
  AuthenticatedProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsCalibrationTechniqueIdRoute =
  AuthenticatedSettingsCalibrationTechniqueIdRouteImport.update({
    id: '/settings_/calibration/$techniqueId',
    path: '/settings/calibration/$techniqueId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/cost': typeof AuthenticatedCostRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/references': typeof AuthenticatedReferencesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/components/$componentId': typeof AuthenticatedComponentsComponentIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/formulas/$formulaId': typeof AuthenticatedFormulasFormulaIdRoute
  '/ingredients/$ingredientId': typeof AuthenticatedIngredientsIngredientIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/production/$sessionId': typeof AuthenticatedProductionSessionIdRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/components/': typeof AuthenticatedComponentsIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/formulas/': typeof AuthenticatedFormulasIndexRoute
  '/ingredients/': typeof AuthenticatedIngredientsIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/production/': typeof AuthenticatedProductionIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/settings/calibration/$techniqueId': typeof AuthenticatedSettingsCalibrationTechniqueIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/cost': typeof AuthenticatedCostRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/references': typeof AuthenticatedReferencesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/components/$componentId': typeof AuthenticatedComponentsComponentIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/formulas/$formulaId': typeof AuthenticatedFormulasFormulaIdRoute
  '/ingredients/$ingredientId': typeof AuthenticatedIngredientsIngredientIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/production/$sessionId': typeof AuthenticatedProductionSessionIdRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/components': typeof AuthenticatedComponentsIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/formulas': typeof AuthenticatedFormulasIndexRoute
  '/ingredients': typeof AuthenticatedIngredientsIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/production': typeof AuthenticatedProductionIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/settings/calibration/$techniqueId': typeof AuthenticatedSettingsCalibrationTechniqueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/cost': typeof AuthenticatedCostRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/references': typeof AuthenticatedReferencesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/components/$componentId': typeof AuthenticatedComponentsComponentIdRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/formulas/$formulaId': typeof AuthenticatedFormulasFormulaIdRoute
  '/_authenticated/ingredients/$ingredientId': typeof AuthenticatedIngredientsIngredientIdRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/production/$sessionId': typeof AuthenticatedProductionSessionIdRoute
  '/_authenticated/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/_authenticated/components/': typeof AuthenticatedComponentsIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/formulas/': typeof AuthenticatedFormulasIndexRoute
  '/_authenticated/ingredients/': typeof AuthenticatedIngredientsIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/production/': typeof AuthenticatedProductionIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/settings_/calibration/$techniqueId': typeof AuthenticatedSettingsCalibrationTechniqueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cost'
    | '/inventory'
    | '/references'
    | '/settings'
    | '/components/$componentId'
    | '/customers/$customerId'
    | '/formulas/$formulaId'
    | '/ingredients/$ingredientId'
    | '/orders/$orderId'
    | '/production/$sessionId'
    | '/products/$productId'
    | '/components/'
    | '/customers/'
    | '/formulas/'
    | '/ingredients/'
    | '/orders/'
    | '/production/'
    | '/products/'
    | '/settings/calibration/$techniqueId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/cost'
    | '/inventory'
    | '/references'
    | '/settings'
    | '/'
    | '/components/$componentId'
    | '/customers/$customerId'
    | '/formulas/$formulaId'
    | '/ingredients/$ingredientId'
    | '/orders/$orderId'
    | '/production/$sessionId'
    | '/products/$productId'
    | '/components'
    | '/customers'
    | '/formulas'
    | '/ingredients'
    | '/orders'
    | '/production'
    | '/products'
    | '/settings/calibration/$techniqueId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/cost'
    | '/_authenticated/inventory'
    | '/_authenticated/references'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/components/$componentId'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/formulas/$formulaId'
    | '/_authenticated/ingredients/$ingredientId'
    | '/_authenticated/orders/$orderId'
    | '/_authenticated/production/$sessionId'
    | '/_authenticated/products/$productId'
    | '/_authenticated/components/'
    | '/_authenticated/customers/'
    | '/_authenticated/formulas/'
    | '/_authenticated/ingredients/'
    | '/_authenticated/orders/'
    | '/_authenticated/production/'
    | '/_authenticated/products/'
    | '/_authenticated/settings_/calibration/$techniqueId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cost': {
      id: '/_authenticated/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof AuthenticatedCostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/references': {
      id: '/_authenticated/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof AuthenticatedReferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/components/': {
      id: '/_authenticated/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof AuthenticatedComponentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/components/$componentId': {
      id: '/_authenticated/components/$componentId'
      path: '/components/$componentId'
      fullPath: '/components/$componentId'
      preLoaderRoute: typeof AuthenticatedComponentsComponentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formulas/': {
      id: '/_authenticated/formulas/'
      path: '/formulas'
      fullPath: '/formulas/'
      preLoaderRoute: typeof AuthenticatedFormulasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formulas/$formulaId': {
      id: '/_authenticated/formulas/$formulaId'
      path: '/formulas/$formulaId'
      fullPath: '/formulas/$formulaId'
      preLoaderRoute: typeof AuthenticatedFormulasFormulaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ingredients/': {
      id: '/_authenticated/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof AuthenticatedIngredientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ingredients/$ingredientId': {
      id: '/_authenticated/ingredients/$ingredientId'
      path: '/ingredients/$ingredientId'
      fullPath: '/ingredients/$ingredientId'
      preLoaderRoute: typeof AuthenticatedIngredientsIngredientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production/': {
      id: '/_authenticated/production/'
      path: '/production'
      fullPath: '/production/'
      preLoaderRoute: typeof AuthenticatedProductionIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production/$sessionId': {
      id: '/_authenticated/production/$sessionId'
      path: '/production/$sessionId'
      fullPath: '/production/$sessionId'
      preLoaderRoute: typeof AuthenticatedProductionSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/$productId': {
      id: '/_authenticated/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthenticatedProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings_/calibration/$techniqueId': {
      id: '/_authenticated/settings_/calibration/$techniqueId'
      path: '/settings/calibration/$techniqueId'
      fullPath: '/settings/calibration/$techniqueId'
      preLoaderRoute: typeof AuthenticatedSettingsCalibrationTechniqueIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCostRoute: typeof AuthenticatedCostRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedReferencesRoute: typeof AuthenticatedReferencesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedComponentsComponentIdRoute: typeof AuthenticatedComponentsComponentIdRoute
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
  AuthenticatedFormulasFormulaIdRoute: typeof AuthenticatedFormulasFormulaIdRoute
  AuthenticatedIngredientsIngredientIdRoute: typeof AuthenticatedIngredientsIngredientIdRoute
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
  AuthenticatedProductionSessionIdRoute: typeof AuthenticatedProductionSessionIdRoute
  AuthenticatedProductsProductIdRoute: typeof AuthenticatedProductsProductIdRoute
  AuthenticatedComponentsIndexRoute: typeof AuthenticatedComponentsIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedFormulasIndexRoute: typeof AuthenticatedFormulasIndexRoute
  AuthenticatedIngredientsIndexRoute: typeof AuthenticatedIngredientsIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedProductionIndexRoute: typeof AuthenticatedProductionIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedSettingsCalibrationTechniqueIdRoute: typeof AuthenticatedSettingsCalibrationTechniqueIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCostRoute: AuthenticatedCostRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedReferencesRoute: AuthenticatedReferencesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedComponentsComponentIdRoute:
    AuthenticatedComponentsComponentIdRoute,
  AuthenticatedCustomersCustomerIdRoute: AuthenticatedCustomersCustomerIdRoute,
  AuthenticatedFormulasFormulaIdRoute: AuthenticatedFormulasFormulaIdRoute,
  AuthenticatedIngredientsIngredientIdRoute:
    AuthenticatedIngredientsIngredientIdRoute,
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
  AuthenticatedProductionSessionIdRoute: AuthenticatedProductionSessionIdRoute,
  AuthenticatedProductsProductIdRoute: AuthenticatedProductsProductIdRoute,
  AuthenticatedComponentsIndexRoute: AuthenticatedComponentsIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedFormulasIndexRoute: AuthenticatedFormulasIndexRoute,
  AuthenticatedIngredientsIndexRoute: AuthenticatedIngredientsIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedProductionIndexRoute: AuthenticatedProductionIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedSettingsCalibrationTechniqueIdRoute:
    AuthenticatedSettingsCalibrationTechniqueIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
